version: "3.8"
services:
  tika:
    image: apache/tika:latest
    ports:
      - "9998:9998"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  api:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
    depends_on:
      - rabbitmq
      - redis
      - tika

  worker:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    volumes:
      - ./:/app
      - uploads:/app/uploads
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - UPLOAD_DIR=/app/uploads
    depends_on:
      - rabbitmq
      - redis
      - tika

volumes:
  uploads:
